TestSuite1: 
     Program:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  3600
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname1
             value: systemtest1
             
        log_throughput:
          - LOG_EVERY_N: 1000
            runtime: 3600
            ticker: 10 
            num_stop: 10
            search_field: application_type
            search_string:
                - SystemTest
            
        log_latency:
          - num_threads: 1
            log_api_type: bulk
            num_of_logs_in_one_bulk: 125
            log_size: 200
            runtime:  3600
            ticker:  5 
TestSuite2a: 
     Program:
        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 3600
           frequency: 10 
           metric_name: systemtest2a
           metric_dimension:
            - key: hostname
              value: systemtest
        metric_throughput:
         - runtime: 3600
           metric_name: systemtest2a
           ticker: 10
           ticker_to_stop: 10
           metric_dimensions:
            - key: hostname
              value: systemtest

        metric_latency:
         - runtime: 3600
           check_ticker: 1
           send_ticker: 10
           timeout: 30
TestSuite2b: 
     Program:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  3600
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname2b
             value: systemtest2b
             
        log_throughput:
          - LOG_EVERY_N: 1000
            runtime: 3600
            ticker: 10
            num_stop: 10
            search_field: application_type
            search_string:
                - SystemTest
            
        log_latency:
          - num_threads: 1
            log_api_type: bulk
            num_of_logs_in_one_bulk: 125
            log_size: 200
            runtime:  3600
            ticker:  5 
            
        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 3600
           frequency: 10 
           metric_name: systemtest2b
           metric_dimension:
            - key: hostname
              value: systemtest
        metric_throughput:
         - runtime: 3600
           metric_name: systemtest2b
           ticker: 10
           ticker_to_stop: 10
           metric_dimensions:
            - key: hostname
              value: systemtest

        metric_latency:
         - runtime: 3600
           check_ticker: 1
           send_ticker: 10
           timeout: 30

TestSuite3: 
     Program:
        logagent_write:
          - log_ever_n: 100
            runtime:  3600
            inp_file_dir: input/
            inp_file_list: 
             - name: sizey400.txt
               frequency: 1
               loglevel: ERROR
             - name: size200.txt
               frequency: 7
               loglevel: INFO  
            outp_file_dir: /var/log/st_test/
            outp_file_name: test.log
            outp_count: 10 
        logagent_latency:
          - check_timeout: 240
            check_ticker: 10 
            search_ticker: 1 
            runtime: 3600
            log_files:
             - file: test.log
               directory: /var/log/st_test/
               log_level: ERROR
               msg_size: 200

        log_throughput:
          - LOG_EVERY_N: 1000
            runtime: 3600
            ticker: 10
            num_stop: 4
            search_field: application_type  <-------??? set by log Agent
            search_string:
                - systemtest               <--------??? set by log Agent
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  3600
           frequency: 8
           log_level: NONE
           dimension:
           - key: hostname3
             value: systemtest3

TestSuite4a: 
     Program:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  3600
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname
             value: systemtest  
         - num_threads: 1
           log_every_n: 10
           log_api_type: bulk
           num_of_logs_in_one_bulk: 1           
           log_size: 200
           runtime:  3600
           frequency: 0.1
           log_level: ERROR
           dimension:
           - key: hostname
             value: systemtestERROR
         - num_threads: 1
           log_every_n: 10
           log_api_type: bulk
           num_of_logs_in_one_bulk: 1
           log_size: 200
           runtime:  3600
           frequency: 0.1
           log_level: WARNING
           dimension:
           - key: hostname
             value: systemtestWARNING
        metric_throughput:
         - runtime: 3600
           metric_name: log.error
           ticker: 10
           ticker_to_stop: 10
           metric_dimensions:
            - key: hostname
              value: systemtestERROR
         - runtime: 3600
           metric_name: log.warning
           ticker: 10
           ticker_to_stop: 10
           metric_dimensions:
             - key: hostname
               value: systemtestWARNING
TestSuite4: 
     Program:
        alarm_on_log:
            runtime : 3600
            alarm_conf:
            - severity: error
              number_of_alarm_def: 5
              alarms_per_alarm_definition: 10
            - severity: warning
              number_of_alarm_def: 5
              alarms_per_alarm_definition: 10
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  3600
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname
             value: alarmLog   
        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 3600
           frequency: 10 
           metric_name: systemtest
           metric_dimension:
            - key: hostname
              value: alarmMertic
TestSuite5:
    Program_before_stress:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  60
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname2b
             value: systemtest2b

        log_throughput:
          - LOG_EVERY_N: 1000
            runtime: 60
            ticker: 2
            num_stop: 10
            search_field: application_type
            search_string:
                - SystemTest

        log_latency:
          - num_threads: 1
            log_api_type: bulk
            num_of_logs_in_one_bulk: 125
            log_size: 200
            runtime:  60
            ticker:  5

        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 60
           frequency: 10
           metric_name: systemtest2b
           metric_dimension:
            - key: hostname
              value: systemtest

        metric_throughput:
         - runtime: 60
           metric_name: systemtest2b
           ticker: 10
           ticker_to_stop: 2
           metric_dimensions:
            - key: hostname
              value: systemtest

        metric_latency:
         - runtime: 60
           check_ticker: 1
           send_ticker: 10
           timeout: 30
    Program_stress:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  60
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname2b
             value: systemtest2b
        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 60
           frequency: 10
           metric_name: systemtest2b
           metric_dimension:
            - key: hostname
              value: systemtest

    Program_after_stress:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 125
           log_size: 200
           runtime:  60
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname2b
             value: systemtest2b

        log_throughput:
          - LOG_EVERY_N: 1000
            runtime: 60
            ticker: 2
            num_stop: 10
            search_field: application_type
            search_string:
                - SystemTest

        log_latency:
          - num_threads: 1
            log_api_type: bulk
            num_of_logs_in_one_bulk: 125
            log_size: 200
            runtime:  60
            ticker:  5

        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 60
           frequency: 10
           metric_name: systemtest2b
           metric_dimension:
            - key: hostname
              value: systemtest

        metric_throughput:
         - runtime: 60
           metric_name: systemtest2b
           ticker: 10
           ticker_to_stop: 2
           metric_dimensions:
            - key: hostname
              value: systemtest

        metric_latency:
         - runtime: 60
           check_ticker: 1
           send_ticker: 10
           timeout: 30



TestSuite6:
     Program:
        log_send:
         - num_threads: 1
           log_every_n: 1000
           log_api_type: bulk
           num_of_logs_in_one_bulk: 10
           log_size: 200
           runtime:  259200
           frequency: 8
           log_level: INFO
           dimension:
           - key: hostname
             value: systemtest

        log_throughput:
          - LOG_EVERY_N: 1000
            runtime: 259200
            ticker: 10
            num_stop: 10
            search_field: application_type
            search_string:
                - SystemTest

        log_latency:
          - num_threads: 1
            log_api_type: bulk
            num_of_logs_in_one_bulk: 125
            log_size: 200
            runtime:  259200
            ticker:  5

        metric_send:
         - num_threads: 1
           num_metrics_per_request: 100
           LOG_EVERY_N: 1000
           runtime: 259200
           frequency: 10
           metric_name: systemtest
           metric_dimension:
            - key: hostname
              value: systemtest


        metric_latency:
         - runtime: 259200
           check_ticker: 1
           send_ticker: 10
           timeout: 30



